### ISSUE TITLE
Appending the 0 for GIAI identifiers when converting from DL WebURI to URN

### ISSUE THREAD

**Issue by Aravinda93** [openepcis/openepcis-epc-digitallink-translator#1]
Dear @RalphTro 

When converting the DL WebURI to URN for GIAI identifiers if GCP length is not provided then we are trying to map the identifier in the list provided by GS1 (https://www.gs1.org/sites/default/files/docs/gcp_length/gcpprefixformatlist.json). But for some identifiers, we are appending `0` at the beginning of the identifier before obtaining the GCP length from the above-provided link.

We would like to know if we should append the `0` to GIAI identifiers or not. Currently, we are taking the reference from the following project: https://github.com/RalphTro/getGCPLengthDemo/blob/master/getGCPLength.py where it's appending the `0`. But if we append the `0` then we are getting the wrong GCP length for some of the know GIAI identifiers so we wanted to confirm if this is the right approach or do need some modification.

We are trying to convert an GIAI identifier for which we know that GCP length is 8 but when it looks via that file its finding it as 0 so we wanted to get confirmation on this and also wanted to confirm on what basis we are appending the 0 for application identifiers.

cc: @sboeckelmann

**Comment by RalphTro** [comment]
Dear @Aravinda93 , 

Thanks for the question, happy to support in this. 

In contrast to e.g. SSCC and GTIN (GS1 AI 00 and 01), the '`keyStartsWithGCP`' dictionary indicates that in the case of a GIAI (GS1 AI 8004), the key value immediatly starts with the GCP ('`'8004': True,`'). And this is correct. 

I think the reason of your question is the example, which indeed starts with a zero. But in this case, the zero is inherent part of the GCP. 
GIAI in the example file: '0180451111ABC987'
Corresponding entry in the GCP length table:       [{ "prefix": "01804", "gcpLength": 10 },](url)

Does this answer your question/does this help you?

Kind regards,
Ralph

**Comment by Aravinda93** [comment]
@RalphTro 

Thanks a lot for the quick response. Please correct me if my understanding is wrong.

By default we need to append `0` to GIAI for identifiers but it may change based on 2 conditions:
If GIAI identifier starts with `0` then we should not append again with `0`.
If GIAI identifier does not start with `0` then we need to append and find the respective GCP length.

Following is the example for which we are trying to find the GCP length and convert to URN:
```
https://id.gs1.org/8004/42512183.SENSOR.TR-07-AVE-583:1
```

Since it does not start with `0` we are appending the `0` and trying to find the GCP length for it and the longest match we could find from the file is `042` which has the GCP length of `0`:
```
{ "prefix": "042", "gcpLength": 0 },
```

Due to which we are unable to convert the WebURI to URN as GCP length should be between 6-12 digits.

Best regards,
Aravinda

**Comment by sboeckelmann** [comment]
Dear @RalphTro ,

well, the issue we are facing is related to a partner's GCP with a known GCP length of 8.
If we simply prepend a 0  we find a match on for a 0 length GCP in the JSON.
The issue might to be a confusion with 12-digit GTINs. 
In your python demo there's always a 0 prepended for these identifiers which imho is not always correct.
The GCP in question is: 425121831
In the JSON we can find gcpLength=8 
```{ "prefix": "4251", "gcpLength": 8 },```
but when prefixing with a 0 it results in
```{ "prefix": "042", "gcpLength": 0 },```

however, we might also be misunderstanding this line in the python script
```    
# Normalise input string so that function works consistently for all GS1 keys
    if (keyStartsWithGCP[aI] == True):
        gs1Key = '0' + gs1Key
```

**Comment by RalphTro** [comment]
Dear @sboeckelmann and @Aravinda93 , 

I just run the Python script taking the example of a GIAI accommoding your GCP in question. For that purpose, I simply appended the example file: 
`print (gcl.getGCPLength('8004', '425121832999XYZ‘))`

As a result, I get 8 - i.e. the correct GCP length. (And, when prefixing this GIAI with a zero, the table returns '0', as indicated). 

It is important to note that the two lines you are refering to in GS1's GCP length table are two separate GCP ranges: the first one is issued by GS1 Germany, the second one isn't. In other words, if '042...' would in this case also return a GCP length of '8', it was wrong. So, the lookup into GS1's GCP length table seems to be working fine IMHO. 

Nonwithstanding the latter: may I ask why you need to separate the GCP from the res tof the key in the first place? :-) If you can use GS1 DL URIs, then why not just go for e.g. 'https://id.gs1.org/8004/42512183SENSOR123'?

**Comment by sboeckelmann** [comment]
Dear @RalphTro,

thank you for testing it out. I think I get it now -  seems like magic in python is here:
```gs1Key[1:(j+1)]) ``` 
your not starting matching on the first digit in gs1Key, but on second. So we just missed something in the pyhton code.

> can use GS1 DL URIs, then why not just go for e.g. 'https://id.gs1.org/8004/42512183SENSOR123'?
I know, but they wanted this dot here .... :unamused: looking really ugly when converted to URN...

Of course we are using GS1 DL when capturing the documents for this project, but for query by URN and for satisfying GS1-EPC-Format and GS1-CBV-XML-Format EPCIS 2.0 content negotiation headers, we are converting all identifiers to URN / DL when indexing to our repository.

**Comment by RalphTro** [comment]
:-) Yes, I think that was the magic back then. 

A pity that you still have to separate the GCP value in this case - as this issue proofs, it makes things a lot easier when you do not need to care about the GCP length. 

Is there anything more I can help you with on this matter?

**Comment by sboeckelmann** [comment]
no thank you, I think we are fine for now. Unfortunately we have to cope with gcp-length to support URNs  ... 😮‍💨 

@Aravinda93 - or do you still have any open questions?

**Comment by Aravinda93** [comment]
@RalphTro 
Thanks a lot for the clarification. No, I do not have any more follow-up questions. Thanks a lot again, wish you a nice evening ahead :) closing the issue.
